chore: temporary workaround
@Kha I had to comment the following lines. It is unclear what is going
on. All stages were building on my machine until I tried to build
using a fresh `build/release` directory. Then, I managed to reproduce
the error in the CI earlier today.
So, I destructively removed the `update-stage0`, and tried to build
using a fresh `build/release`. Then, I get the following error at
stage 1.
```
error: no such file or directory (error code: 2)
  file: /Users/leonardodemoura/projects/lean4/build/release/stage1/bin/../lib/lean/Std
```
The error seems to be produced by the line I have commented. It is
a weird bug since I do have the directory
```
/Users/leonardodemoura/projects/lean4/build/release/stage1/lib/lean/Std
```
Note that it works for
```
/Users/leonardodemoura/projects/lean4/build/release/stage1/bin/../lib/lean/Init`
```
No idea why it doesn't work for `Std`.
Anyway, by commenting the lines in this commit I can build all stages
locally. The test `binomial.lean` doesn't work since `Std` is not in
the builtin path.