feat: Improve error messages when monad is unknown
The patch also eliminates the unused `hasBindInst` field
of ExtractMonadResult.

--

partial def foo (u: Unit) : OptionM Nat := do
  return $ 42

Before: error: invalid 'do' notation, expected type is not available
After:

error: function expected at
  pure PUnit.unit
term has type
  Id PUnit

--

partial def bar (i: Int) := do
  return k

Before: do.lean:1:28: error: invalid 'do' notation, expected type is not available
After:  do.lean:2:9: error: unknown identifier 'k'

--

partial def bar (i: Int) := do
  return _

Before: error: invalid 'do' notation, expected type is not available
After: do.lean:2:2: error: typeclass instance problem is stuck, it is often due to metavariables
         Pure (?m.59 i)